export const CURATED_CATEGORIES: Record<string, { name: string; domain: string }[]> = {
  ai: [
    { name: "OpenAI", domain: "openai.com" },
    { name: "Anthropic", domain: "anthropic.com" },
    { name: "Midjourney", domain: "midjourney.com" },
    { name: "Stability AI", domain: "stability.ai" },
    { name: "Hugging Face", domain: "huggingface.co" },
    { name: "Perplexity", domain: "perplexity.ai" },
    { name: "Jasper", domain: "perplexity.ai" },
    { name: "Runway", domain: "runwayml.com" },
    { name: "Cohere", domain: "cohere.com" },
    { name: "Character.ai", domain: "character.ai" },
    { name: "Scale AI", domain: "scale.com" },
    { name: "Copy.ai", domain: "copy.ai" },
    { name: "Synthesia", domain: "runwayml.com" },
    { name: "DeepMind", domain: "deepmind.google" },
    { name: "Nvidia", domain: "nvidia.com" },
    { name: "Mistral AI", domain: "mistral.ai" },
    { name: "CoreWeave", domain: "coreweave.com" },
    { name: "Databricks", domain: "databricks.com" },
    { name: "Groq", domain: "groq.com" },
    { name: "ElevenLabs", domain: "elevenlabs.io" },
    { name: "Harvey", domain: "useharvey.com" },
    { name: "Glean", domain: "glean.com" },
    { name: "Inflection", domain: "inflection.ai" },
    { name: "Together AI", domain: "together.ai" },
    { name: "Figure", domain: "figure.ai" },
    { name: "Pika", domain: "pika.art" },
    { name: "Suno", domain: "suno.ai" },
    { name: "Udio", domain: "udio.com" },
    { name: "Luma AI", domain: "lumalabs.ai" },
    { name: "Civitai", domain: "civitai.com" },
    { name: "Leonardo.ai", domain: "leonardo.ai" },
    { name: "Replicate", domain: "replicate.com" },
    { name: "LangChain", domain: "langchain.com" },
    { name: "Pinecone", domain: "pinecone.io" },
    { name: "Weaviate", domain: "weaviate.io" },
    { name: "Weights & Biases", domain: "wandb.ai" },
    { name: "Modal", domain: "modal.com" },
    { name: "Vercel", domain: "vercel.com" },
    { name: "Replit", domain: "replit.com" },
    { name: "Cursor", domain: "cursor.sh" },
    { name: "Supermaven", domain: "supermaven.com" },
    { name: "Codeium", domain: "codeium.com" },
    { name: "Tabnine", domain: "tabnine.com" },
    { name: "Github Copilot", domain: "github.com" },
    { name: "Descript", domain: "descript.com" },
    { name: "Otter.ai", domain: "otter.ai" },
    { name: "Beautiful.ai", domain: "beautiful.ai" },
    { name: "Gamma", domain: "gamma.app" },
    { name: "Tome", domain: "tome.app" },
    { name: "Notion", domain: "notion.so" }
  ],
  saas: [
    { name: "Salesforce", domain: "salesforce.com" },
    { name: "HubSpot", domain: "hubspot.com" },
    { name: "Zoom", domain: "zoom.us" },
    { name: "Slack", domain: "slack.com" },
    { name: "Atlassian", domain: "atlassian.com" },
    { name: "Adobe", domain: "adobe.com" },
    { name: "Intuit", domain: "intuit.com" },
    { name: "ServiceNow", domain: "servicenow.com" },
    { name: "Workday", domain: "workday.com" },
    { name: "Snowflake", domain: "snowflake.com" },
    { name: "Shopify", domain: "shopify.com" },
    { name: "Square", domain: "squareup.com" },
    { name: "Stripe", domain: "stripe.com" },
    { name: "Twilio", domain: "twilio.com" },
    { name: "Okta", domain: "okta.com" },
    { name: "DocuSign", domain: "docusign.com" },
    { name: "CrowdStrike", domain: "crowdstrike.com" },
    { name: "Zscaler", domain: "zscaler.com" },
    { name: "Datadog", domain: "datadog.com" },
    { name: "MongoDB", domain: "mongodb.com" },
    { name: "Cloudflare", domain: "cloudflare.com" },
    { name: "Palantir", domain: "palantir.com" },
    { name: "Veeva", domain: "veeva.com" },
    { name: "Autodesk", domain: "adobe.com" },
    { name: "Canva", domain: "canva.com" },
    { name: "Figma", domain: "figma.com" },
    { name: "Miro", domain: "miro.com" },
    { name: "Airtable", domain: "airtable.com" },
    { name: "Monday.com", domain: "monday.com" },
    { name: "Asana", domain: "asana.com" },
    { name: "Trello", domain: "trello.com" },
    { name: "Linear", domain: "linear.app" },
    { name: "ClickUp", domain: "clickup.com" },
    { name: "Dropbox", domain: "dropbox.com" },
    { name: "Box", domain: "dropbox.com" },
    { name: "Zendesk", domain: "zendesk.com" },
    { name: "Intercom", domain: "intercom.com" },
    { name: "Freshworks", domain: "freshworks.com" },
    { name: "Typeform", domain: "typeform.com" },
    { name: "Loom", domain: "loom.com" },
    { name: "Zapier", domain: "zapier.com" },
    { name: "Webflow", domain: "webflow.com" },
    { name: "Framer", domain: "framer.com" },
    { name: "Wix", domain: "wix.com" },
    { name: "Squarespace", domain: "squarespace.com" },
    { name: "Mailchimp", domain: "mailchimp.com" },
    { name: "Klaviyo", domain: "klaviyo.com" },
    { name: "Brex", domain: "brex.com" },
    { name: "Rippling", domain: "rippling.com" },
    { name: "Deel", domain: "deel.com" }
  ],
  finance: [
    { name: "Stripe", domain: "stripe.com" },
    { name: "PayPal", domain: "paypal.com" },
    { name: "Square", domain: "squareup.com" },
    { name: "Visa", domain: "visa.com" },
    { name: "Mastercard", domain: "mastercard.com" },
    { name: "Amex", domain: "americanexpress.com" },
    { name: "Chase", domain: "chase.com" },
    { name: "Goldman Sachs", domain: "goldmansachs.com" },
    { name: "Morgan Stanley", domain: "morganstanley.com" },
    { name: "BlackRock", domain: "blackrock.com" },
    { name: "Robinhood", domain: "robinhood.com" },
    { name: "Coinbase", domain: "coinbase.com" },
    { name: "Revolut", domain: "revolut.com" },
    { name: "Nubank", domain: "revolut.com" },
    { name: "Monzo", domain: "monzo.com" },
    { name: "Chime", domain: "chime.com" },
    { name: "Wise", domain: "wise.com" },
    { name: "Klarna", domain: "klarna.com" },
    { name: "Affirm", domain: "affirm.com" },
    { name: "SoFi", domain: "sofi.com" },
    { name: "Wealthfront", domain: "wealthfront.com" },
    { name: "Betterment", domain: "betterment.com" },
    { name: "Acorns", domain: "acorns.com" },
    { name: "Plaid", domain: "plaid.com" },
    { name: "Brex", domain: "brex.com" },
    { name: "Ramp", domain: "ramp.com" },
    { name: "Mercury", domain: "mercury.com" },
    { name: "Navan", domain: "navan.com" },
    { name: "Bill", domain: "bill.com" },
    { name: "Expensify", domain: "expensify.com" },
    { name: "Gusto", domain: "gusto.com" },
    { name: "Adyen", domain: "adyen.com" },
    { name: "Checkout.com", domain: "checkout.com" },
    { name: "Worldpay", domain: "worldpay.com" },
    { name: "Fidelity", domain: "fidelity.com" },
    { name: "Vanguard", domain: "vanguard.com" },
    { name: "Charles Schwab", domain: "schwab.com" },
    { name: "Citadel", domain: "citadel.com" },
    { name: "Bridgewater", domain: "citadel.com" },
    { name: "Two Sigma", domain: "twosigma.com" },
    { name: "Jane Street", domain: "janestreet.com" },
    { name: "Carta", domain: "carta.com" },
    { name: "AngelList", domain: "carta.com" },
    { name: "Upstart", domain: "upstart.com" },
    { name: "LendingClub", domain: "lendingclub.com" },
    { name: "Credit Karma", domain: "creditkarma.com" },
    { name: "Mint", domain: "intuit.com" },
    { name: "YNAB", domain: "ynab.com" },
    { name: "Quickbooks", domain: "quickbooks.intuit.com" },
    { name: "Xero", domain: "xero.com" }
  ],
  social: [
    { name: "Meta", domain: "meta.com" },
    { name: "Facebook", domain: "facebook.com" },
    { name: "Instagram", domain: "instagram.com" },
    { name: "WhatsApp", domain: "whatsapp.com" },
    { name: "TikTok", domain: "tiktok.com" },
    { name: "Twitter/X", domain: "x.com" },
    { name: "LinkedIn", domain: "linkedin.com" },
    { name: "Snapchat", domain: "snapchat.com" },
    { name: "Pinterest", domain: "pinterest.com" },
    { name: "Reddit", domain: "reddit.com" },
    { name: "Discord", domain: "discord.com" },
    { name: "Telegram", domain: "telegram.org" },
    { name: "Twitch", domain: "twitch.tv" },
    { name: "YouTube", domain: "youtube.com" },
    { name: "Vimeo", domain: "vimeo.com" },
    { name: "Tumblr", domain: "tumblr.com" },
    { name: "WeChat", domain: "wechat.com" },
    { name: "Line", domain: "line.me" },
    { name: "Signal", domain: "signal.org" },
    { name: "Clubhouse", domain: "clubhouse.com" },
    { name: "BeReal", domain: "bereal.com" },
    { name: "Threads", domain: "threads.net" },
    { name: "Bluesky", domain: "bsky.app" },
    { name: "Mastodon", domain: "mastodon.social" },
    { name: "Medium", domain: "medium.com" },
    { name: "Substack", domain: "substack.com" },
    { name: "Patreon", domain: "patreon.com" },
    { name: "OnlyFans", domain: "onlyfans.com" },
    { name: "Cameo", domain: "cameo.com" },
    { name: "Linktree", domain: "linktr.ee" },
    { name: "Bumble", domain: "bumble.com" },
    { name: "Tinder", domain: "tinder.com" },
    { name: "Hinge", domain: "hinge.co" },
    { name: "Grindr", domain: "grindr.com" },
    { name: "Match", domain: "match.com" },
    { name: "OkCupid", domain: "okcupid.com" },
    { name: "Flickr", domain: "flickr.com" },
    { name: "500px", domain: "500px.com" },
    { name: "Imgur", domain: "imgur.com" },
    { name: "Giphy", domain: "giphy.com" },
    { name: "9GAG", domain: "9gag.com" },
    { name: "Quora", domain: "quora.com" },
    { name: "Stack Overflow", domain: "stackoverflow.com" },
    { name: "Blind", domain: "teamblind.com" },
    { name: "Nextdoor", domain: "nextdoor.com" },
    { name: "Meetup", domain: "meetup.com" },
    { name: "Eventbrite", domain: "meetup.com" },
    { name: "Strava", domain: "strava.com" },
    { name: "AllTrails", domain: "alltrails.com" },
    { name: "Letterboxd", domain: "letterboxd.com" }
  ],
  crypto: [
    { name: "Bitcoin", domain: "bitcoin.org" },
    { name: "Ethereum", domain: "ethereum.org" },
    { name: "Solana", domain: "solana.com" },
    { name: "Binance", domain: "binance.com" },
    { name: "Coinbase", domain: "coinbase.com" },
    { name: "Kraken", domain: "kraken.com" },
    { name: "Crypto.com", domain: "crypto.com" },
    { name: "Gemini", domain: "gemini.com" },
    { name: "FTX", domain: "gemini.com" },
    { name: "Bybit", domain: "bybit.com" },
    { name: "KuCoin", domain: "kucoin.com" },
    { name: "OKX", domain: "okx.com" },
    { name: "Uniswap", domain: "uniswap.org" },
    { name: "OpenSea", domain: "opensea.io" },
    { name: "Metamask", domain: "metamask.io" },
    { name: "Trust Wallet", domain: "trustwallet.com" },
    { name: "Ledger", domain: "ledger.com" },
    { name: "Trezor", domain: "trezor.io" },
    { name: "Phantom", domain: "phantom.app" },
    { name: "Rainbow", domain: "rainbow.me" },
    { name: "Circle", domain: "circle.com" },
    { name: "Tether", domain: "tether.to" },
    { name: "Ripple", domain: "ripple.com" },
    { name: "Chainlink", domain: "chain.link" },
    { name: "Polygon", domain: "polygon.technology" },
    { name: "Avalanche", domain: "avax.network" },
    { name: "Arbitrum", domain: "arbitrum.io" },
    { name: "Optimism", domain: "optimism.io" },
    { name: "Base", domain: "base.org" },
    { name: "Starknet", domain: "starknet.io" },
    { name: "Aave", domain: "aave.com" },
    { name: "Compound", domain: "compound.finance" },
    { name: "MakerDAO", domain: "makerdao.com" },
    { name: "Curve", domain: "curve.fi" },
    { name: "Lido", domain: "lido.fi" },
    { name: "Rocket Pool", domain: "rocketpool.net" },
    { name: "Blur", domain: "blur.io" },
    { name: "Magic Eden", domain: "magiceden.io" },
    { name: "Rarible", domain: "rarible.com" },
    { name: "SuperRare", domain: "superrare.com" },
    { name: "Foundation", domain: "foundation.app" },
    { name: "Zora", domain: "zora.co" },
    { name: "Dune", domain: "dune.com" },
    { name: "Nansen", domain: "nansen.ai" },
    { name: "Messari", domain: "messari.io" },
    { name: "CoinGecko", domain: "coingecko.com" },
    { name: "CoinMarketCap", domain: "coingecko.com" },
    { name: "TradingView", domain: "tradingview.com" },
    { name: "DefiLlama", domain: "defillama.com" },
    { name: "Etherscan", domain: "etherscan.io" }
  ],
  shop: [
    { name: "Amazon", domain: "amazon.com" },
    { name: "Walmart", domain: "walmart.com" },
    { name: "Target", domain: "target.com" },
    { name: "Costco", domain: "costco.com" },
    { name: "Nike", domain: "nike.com" },
    { name: "Adidas", domain: "adidas.com" },
    { name: "Shopify", domain: "shopify.com" },
    { name: "Etsy", domain: "etsy.com" },
    { name: "eBay", domain: "ebay.com" },
    { name: "AliExpress", domain: "aliexpress.com" },
    { name: "Temu", domain: "temu.com" },
    { name: "Shein", domain: "shein.com" },
    { name: "Best Buy", domain: "bestbuy.com" },
    { name: "Home Depot", domain: "homedepot.com" },
    { name: "Lowe\"s", domain: "lowes.com" },
    { name: "IKEA", domain: "ikea.com" },
    { name: "Wayfair", domain: "wayfair.com" },
    { name: "Zara", domain: "zara.com" },
    { name: "H&M", domain: "hm.com" },
    { name: "Uniqlo", domain: "uniqlo.com" },
    { name: "ASOS", domain: "asos.com" },
    { name: "Lululemon", domain: "lululemon.com" },
    { name: "Sephora", domain: "sephora.com" },
    { name: "Ulta", domain: "ulta.com" },
    { name: "Nordstrom", domain: "nordstrom.com" },
    { name: "Macy\"s", domain: "macys.com" },
    { name: "Bloomingdale\"s", domain: "bloomingdales.com" },
    { name: "Saks Fifth Avenue", domain: "saksfifthavenue.com" },
    { name: "Neiman Marcus", domain: "neimanmarcus.com" },
    { name: "Gucci", domain: "gucci.com" },
    { name: "Louis Vuitton", domain: "louisvuitton.com" },
    { name: "Prada", domain: "prada.com" },
    { name: "Chanel", domain: "chanel.com" },
    { name: "Hermès", domain: "hermes.com" },
    { name: "Dior", domain: "dior.com" },
    { name: "Tiffany & Co.", domain: "tiffany.com" },
    { name: "Cartier", domain: "cartier.com" },
    { name: "Rolex", domain: "rolex.com" },
    { name: "Patek Philippe", domain: "rolex.com" },
    { name: "Warby Parker", domain: "warbyparker.com" },
    { name: "Allbirds", domain: "allbirds.com" },
    { name: "Gymshark", domain: "gymshark.com" },
    { name: "Glossier", domain: "glossier.com" },
    { name: "Fenty Beauty", domain: "fentybeauty.com" },
    { name: "Kylie Cosmetics", domain: "kyliecosmetics.com" },
    { name: "Skims", domain: "skims.com" },
    { name: "Yeti", domain: "yeti.com" },
    { name: "Patagonia", domain: "yeti.com" },
    { name: "The North Face", domain: "patagonia.com" },
    { name: "REI", domain: "rei.com" }
  ]
}

export const TOP_100_COMPANIES = [
  ...CURATED_CATEGORIES.ai.slice(0, 30),
  ...CURATED_CATEGORIES.saas.slice(0, 20),
  ...CURATED_CATEGORIES.finance.slice(0, 15),
  ...CURATED_CATEGORIES.social.slice(0, 15),
  ...CURATED_CATEGORIES.shop.slice(0, 10),
  { name: "Google", domain: "google.com" },
  { name: "Microsoft", domain: "microsoft.com" },
  { name: "Apple", domain: "apple.com" },
  { name: "Netflix", domain: "netflix.com" },
  { name: "Tesla", domain: "tesla.com" },
  { name: "SpaceX", domain: "spacex.com" },
  { name: "Uber", domain: "uber.com" },
  { name: "Airbnb", domain: "airbnb.com" },
  { name: "Spotify", domain: "spotify.com" },
  { name: "Coca-Cola", domain: "coca-colacompany.com" }
]
