export const CURATED_CATEGORIES: Record<string, { name: string; domain: string }[]> = {
  ai: [
    { name: "OpenAI", domain: "openai.com" },
    { name: "Anthropic", domain: "anthropic.com" },
    { name: "Midjourney", domain: "midjourney.com" },
    { name: "Stability AI", domain: "stability.ai" },
    { name: "Hugging Face", domain: "huggingface.co" },
    { name: "Jasper", domain: "jasper.ai" },
    { name: "Copy.ai", "domain": "copy.ai" },
    { name: "Runway", domain: "runwayml.com" },
    { name: "Character.ai", "domain": "character.ai" },
    { name: "Perplexity", "domain": "perplexity.ai" },
    { name: "Scale AI", "domain": "scale.com" },
    { name: "DeepMind", "domain": "deepmind.google" },
    { name: "Cohere", "domain": "cohere.com" },
    { name: "Mistral AI", "domain": "mistral.ai" },
    { name: "Inflection AI", "domain": "inflection.ai" },
    { name: "Synthesia", "domain": "synthesia.io" },
    { name: "Descript", "domain": "descript.com" },
    { name: "NVIDIA", "domain": "nvidia.com" },
    { name: "Microsoft", "domain": "microsoft.com" },
    { name: "Google", "domain": "google.com" },
    { name: "Meta", "domain": "meta.com" },
    { name: "Adobe", "domain": "adobe.com" },
    { name: "GitHub Copilot", "domain": "github.com" },
    { name: "Tabnine", "domain": "tabnine.com" },
    { name: "Replicate", "domain": "replicate.com" },
    { name: "Weights & Biases", "domain": "wandb.ai" },
    { name: "Pinecone", "domain": "pinecone.io" },
    { name: "Weaviate", "domain": "weaviate.io" },
    { name: "LangChain", "domain": "langchain.com" },
    { name: "LlamaIndex", "domain": "llamaindex.ai" },
    { name: "Glean", "domain": "glean.com" },
    { name: "Harvey", "domain": "harvey.ai" },
    { name: "Typeface", "domain": "typeface.ai" },
    { name: "Tome", "domain": "tome.app" },
    { name: "Gamma", "domain": "gamma.app" },
    { name: "Beautiful.ai", "domain": "beautiful.ai" },
    { name: "Otter.ai", "domain": "otter.ai" },
    { name: "Fireflies.ai", "domain": "fireflies.ai" },
    { name: "Rewind", "domain": "rewind.ai" },
    { name: "Mem", "domain": "mem.ai" },
    { name: "Notion", "domain": "notion.so" },
    { name: "Canva", "domain": "canva.com" },
    { name: "Grammarly", "domain": "grammarly.com" },
    { name: "DeepL", "domain": "deepl.com" },
    { name: "Quillbot", "domain": "quillbot.com" },
    { name: "Wordtune", "domain": "wordtune.com" },
    { name: "Writesonic", "domain": "writesonic.com" },
    { name: "Rytr", "domain": "rytr.me" },
    { name: "Anyword", "domain": "anyword.com" },
    { name: "Simplified", "domain": "simplified.com" }
  ],
  saas: [
    { name: "Salesforce", domain: "salesforce.com" },
    { name: "HubSpot", domain: "hubspot.com" },
    { name: "Zoom", domain: "zoom.us" },
    { name: "Slack", domain: "slack.com" },
    { name: "Atlassian", domain: "atlassian.com" },
    { name: "Jira", domain: "jira.com" },
    { name: "Trello", domain: "trello.com" },
    { name: "Asana", domain: "asana.com" },
    { name: "Monday.com", domain: "monday.com" },
    { name: "ClickUp", domain: "clickup.com" },
    { name: "Airtable", domain: "airtable.com" },
    { name: "Snowflake", domain: "snowflake.com" },
    { name: "Datadog", domain: "datadoghq.com" },
    { name: "Splunk", domain: "splunk.com" },
    { name: "ServiceNow", domain: "servicenow.com" },
    { name: "Workday", domain: "workday.com" },
    { name: "Oracle", domain: "oracle.com" },
    { name: "SAP", domain: "sap.com" },
    { name: "Intuit", domain: "intuit.com" },
    { name: "QuickBooks", domain: "quickbooks.intuit.com" },
    { name: "Mailchimp", domain: "mailchimp.com" },
    { name: "Shopify", domain: "shopify.com" },
    { name: "Square", domain: "squareup.com" },
    { name: "Stripe", domain: "stripe.com" },
    { name: "Twilio", domain: "twilio.com" },
    { name: "Zendesk", domain: "zendesk.com" },
    { name: "Intercom", domain: "intercom.com" },
    { name: "Drift", domain: "drift.com" },
    { name: "Figma", domain: "figma.com" },
    { name: "Miro", domain: "miro.com" },
    { name: "Loom", domain: "loom.com" },
    { name: "Dropbox", domain: "dropbox.com" },
    { name: "Box", domain: "box.com" },
    { name: "DocuSign", domain: "docusign.com" },
    { name: "PandaDoc", domain: "pandadoc.com" },
    { name: "Deel", domain: "deel.com" },
    { name: "Rippling", domain: "rippling.com" },
    { name: "Gusto", domain: "gusto.com" },
    { name: "BambooHR", domain: "bamboohr.com" },
    { name: "Greenhouse", domain: "greenhouse.io" },
    { name: "Lever", domain: "lever.co" },
    { name: "Lattice", domain: "lattice.com" },
    { name: "15Five", domain: "15five.com" },
    { name: "Culture Amp", domain: "cultureamp.com" },
    { name: "Webflow", domain: "webflow.com" },
    { name: "Wix", domain: "wix.com" },
    { name: "Squarespace", domain: "squarespace.com" },
    { name: "WordPress", domain: "wordpress.com" },
    { name: "Ghost", domain: "ghost.org" },
    { name: "Substack", domain: "substack.com" }
  ],
  fintech: [
    { name: "Stripe", domain: "stripe.com" },
    { name: "PayPal", domain: "paypal.com" },
    { name: "Square", domain: "squareup.com" },
    { name: "Block", domain: "block.xyz" },
    { name: "Adyen", domain: "adyen.com" },
    { name: "Revolut", domain: "revolut.com" },
    { name: "Wise", domain: "wise.com" },
    { name: "Monzo", domain: "monzo.com" },
    { name: "N26", domain: "n26.com" },
    { name: "Chime", domain: "chime.com" },
    { name: "Robinhood", domain: "robinhood.com" },
    { name: "Coinbase", domain: "coinbase.com" },
    { name: "Binance", domain: "binance.com" },
    { name: "Kraken", domain: "kraken.com" },
    { name: "Plaid", domain: "plaid.com" },
    { name: "Brex", domain: "brex.com" },
    { name: "Ramp", domain: "ramp.com" },
    { name: "Mercury", domain: "mercury.com" },
    { name: "Carta", domain: "carta.com" },
    { name: "Klarna", domain: "klarna.com" },
    { name: "Affirm", domain: "affirm.com" },
    { name: "Afterpay", domain: "afterpay.com" },
    { name: "Nubank", domain: "nubank.com.br" },
    { name: "SoFi", domain: "sofi.com" },
    { name: "Wealthfront", domain: "wealthfront.com" },
    { name: "Betterment", domain: "betterment.com" },
    { name: "Acorns", domain: "acorns.com" },
    { name: "Stash", domain: "stash.com" },
    { name: "eToro", domain: "etoro.com" },
    { name: "Public", domain: "public.com" },
    { name: "Cash App", domain: "cash.app" },
    { name: "Venmo", domain: "venmo.com" },
    { name: "Zelle", domain: "zellepay.com" },
    { name: "Remitly", domain: "remitly.com" },
    { name: "WorldRemit", domain: "worldremit.com" },
    { name: "Bill.com", domain: "bill.com" },
    { name: "Expensify", domain: "expensify.com" },
    { name: "Navan", domain: "navan.com" },
    { name: "Xero", domain: "xero.com" },
    { name: "FreshBooks", domain: "freshbooks.com" },
    { name: "Wave", domain: "waveapps.com" },
    { name: "Melio", domain: "meliopayments.com" },
    { name: "Marqeta", domain: "marqeta.com" },
    { name: "Checkout.com", domain: "checkout.com" },
    { name: "Bolt", domain: "bolt.com" },
    { name: "Fast", domain: "fast.co" },
    { name: "Toast", domain: "toasttab.com" },
    { name: "Lightspeed", domain: "lightspeedhq.com" },
    { name: "ShopKeep", domain: "shopkeep.com" },
    { name: "Clover", domain: "clover.com" }
  ],
  social: [
    { name: "Facebook", domain: "facebook.com" },
    { name: "Instagram", domain: "instagram.com" },
    { name: "Twitter", domain: "twitter.com" },
    { name: "X", domain: "x.com" },
    { name: "LinkedIn", domain: "linkedin.com" },
    { name: "TikTok", domain: "tiktok.com" },
    { name: "Snapchat", domain: "snapchat.com" },
    { name: "Pinterest", domain: "pinterest.com" },
    { name: "Reddit", domain: "reddit.com" },
    { name: "Discord", domain: "discord.com" },
    { name: "YouTube", domain: "youtube.com" },
    { name: "Twitch", domain: "twitch.tv" },
    { name: "WhatsApp", domain: "whatsapp.com" },
    { name: "Messenger", domain: "messenger.com" },
    { name: "Telegram", domain: "telegram.org" },
    { name: "Signal", domain: "signal.org" },
    { name: "WeChat", domain: "wechat.com" },
    { name: "Line", domain: "line.me" },
    { name: "KakaoTalk", domain: "kakaocorp.com" },
    { name: "Viber", domain: "viber.com" },
    { name: "Clubhouse", domain: "clubhouse.com" },
    { name: "BeReal", domain: "bereal.com" },
    { name: "Threads", domain: "threads.net" },
    { name: "Bluesky", domain: "bsky.app" },
    { name: "Mastodon", domain: "joinmastodon.org" },
    { name: "Tumblr", domain: "tumblr.com" },
    { name: "Flickr", domain: "flickr.com" },
    { name: "Quora", domain: "quora.com" },
    { name: "Medium", domain: "medium.com" },
    { name: "Substack", domain: "substack.com" },
    { name: "Patreon", domain: "patreon.com" },
    { name: "OnlyFans", domain: "onlyfans.com" },
    { name: "Cameo", domain: "cameo.com" },
    { name: "Linktree", domain: "linktr.ee" },
    { name: "Bumble", domain: "bumble.com" },
    { name: "Tinder", domain: "tinder.com" },
    { name: "Hinge", domain: "hinge.co" },
    { name: "Match", domain: "match.com" },
    { name: "OkCupid", domain: "okcupid.com" },
    { name: "Grindr", domain: "grindr.com" },
    { name: "Strava", domain: "strava.com" },
    { name: "Nextdoor", domain: "nextdoor.com" },
    { name: "Yelp", domain: "yelp.com" },
    { name: "TripAdvisor", domain: "tripadvisor.com" },
    { name: "Foursquare", domain: "foursquare.com" },
    { name: "Meetup", domain: "meetup.com" },
    { name: "Eventbrite", domain: "eventbrite.com" },
    { name: "Luma", domain: "lu.ma" },
    { name: "Partiful", domain: "partiful.com" },
    { name: "Slack", domain: "slack.com" }
  ],
  crypto: [
    { name: "Bitcoin", domain: "bitcoin.org" },
    { name: "Ethereum", domain: "ethereum.org" },
    { name: "Binance", domain: "binance.com" },
    { name: "Coinbase", domain: "coinbase.com" },
    { name: "Kraken", domain: "kraken.com" },
    { name: "Crypto.com", domain: "crypto.com" },
    { name: "Gemini", domain: "gemini.com" },
    { name: "KuCoin", domain: "kucoin.com" },
    { name: "Bybit", domain: "bybit.com" },
    { name: "OKX", domain: "okx.com" },
    { name: "Bitfinex", domain: "bitfinex.com" },
    { name: "Huobi", domain: "huobi.com" },
    { name: "Gate.io", domain: "gate.io" },
    { name: "Bitstamp", domain: "bitstamp.net" },
    { name: "eToro", domain: "etoro.com" },
    { name: "Robinhood", domain: "robinhood.com" },
    { name: "Metamask", domain: "metamask.io" },
    { name: "Trust Wallet", domain: "trustwallet.com" },
    { name: "Ledger", domain: "ledger.com" },
    { name: "Trezor", domain: "trezor.io" },
    { name: "Exodus", domain: "exodus.com" },
    { name: "Phantom", domain: "phantom.app" },
    { name: "Uniswap", domain: "uniswap.org" },
    { name: "PancakeSwap", domain: "pancakeswap.finance" },
    { name: "SushiSwap", domain: "sushi.com" },
    { name: "Curve", domain: "curve.fi" },
    { name: "Aave", domain: "aave.com" },
    { name: "Compound", domain: "compound.finance" },
    { name: "MakerDAO", domain: "makerdao.com" },
    { name: "OpenSea", domain: "opensea.io" },
    { name: "Rarible", domain: "rarible.com" },
    { name: "Magic Eden", domain: "magiceden.io" },
    { name: "Blur", domain: "blur.io" },
    { name: "LooksRare", domain: "looksrare.org" },
    { name: "Yuga Labs", domain: "yuga.com" },
    { name: "Dapper Labs", domain: "dapperlabs.com" },
    { name: "Chainlink", domain: "chain.link" },
    { name: "Polygon", domain: "polygon.technology" },
    { name: "Solana", domain: "solana.com" },
    { name: "Avalanche", domain: "avax.network" },
    { name: "Cardano", domain: "cardano.org" },
    { name: "Polkadot", domain: "polkadot.network" },
    { name: "Ripple", domain: "ripple.com" },
    { name: "Stellar", domain: "stellar.org" },
    { name: "Near", domain: "near.org" },
    { name: "Arbitrum", domain: "arbitrum.io" },
    { name: "Optimism", domain: "optimism.io" },
    { name: "Base", domain: "base.org" },
    { name: "Circle", domain: "circle.com" },
    { name: "Tether", domain: "tether.to" }
  ],
  shop: [
    { name: "Amazon", domain: "amazon.com" },
    { name: "eBay", domain: "ebay.com" },
    { name: "Walmart", domain: "walmart.com" },
    { name: "Target", domain: "target.com" },
    { name: "Best Buy", domain: "bestbuy.com" },
    { name: "Costco", domain: "costco.com" },
    { name: "Home Depot", domain: "homedepot.com" },
    { name: "Lowe's", domain: "lowes.com" },
    { name: "IKEA", domain: "ikea.com" },
    { name: "Wayfair", domain: "wayfair.com" },
    { name: "Etsy", domain: "etsy.com" },
    { name: "Shopify", domain: "shopify.com" },
    { name: "Alibaba", domain: "alibaba.com" },
    { name: "AliExpress", domain: "aliexpress.com" },
    { name: "Temu", domain: "temu.com" },
    { name: "Shein", domain: "shein.com" },
    { name: "Zara", domain: "zara.com" },
    { name: "H&M", domain: "hm.com" },
    { name: "Uniqlo", domain: "uniqlo.com" },
    { name: "Nike", domain: "nike.com" },
    { name: "Adidas", domain: "adidas.com" },
    { name: "Lululemon", domain: "lululemon.com" },
    { name: "Sephora", domain: "sephora.com" },
    { name: "Ulta Beauty", domain: "ulta.com" },
    { name: "Macy's", domain: "macys.com" },
    { name: "Nordstrom", domain: "nordstrom.com" },
    { name: "Bloomingdale's", domain: "bloomingdales.com" },
    { name: "Saks Fifth Avenue", domain: "saksfifthavenue.com" },
    { name: "Neiman Marcus", domain: "neimanmarcus.com" },
    { name: "ASOS", domain: "asos.com" },
    { name: "Zalando", domain: "zalando.com" },
    { name: "Farfetch", domain: "farfetch.com" },
    { name: "Net-a-Porter", domain: "net-a-porter.com" },
    { name: "SSENSE", domain: "ssense.com" },
    { name: "StockX", domain: "stockx.com" },
    { name: "Goat", domain: "goat.com" },
    { name: "Chewy", domain: "chewy.com" },
    { name: "PetSmart", domain: "petsmart.com" },
    { name: "Petco", domain: "petco.com" },
    { name: "CVS", domain: "cvs.com" },
    { name: "Walgreens", domain: "walgreens.com" },
    { name: "Rite Aid", domain: "riteaid.com" },
    { name: "Kroger", domain: "kroger.com" },
    { name: "Whole Foods", domain: "wholefoodsmarket.com" },
    { name: "Trader Joe's", domain: "traderjoes.com" },
    { name: "Aldi", domain: "aldi.us" },
    { name: "Lidl", domain: "lidl.com" },
    { name: "Instacart", domain: "instacart.com" },
    { name: "DoorDash", domain: "doordash.com" },
    { name: "Uber Eats", domain: "ubereats.com" }
  ]
};

export const TOP_100_COMPANIES = [
  ...CURATED_CATEGORIES.ai.slice(0, 30),
  ...CURATED_CATEGORIES.saas.slice(0, 20),
  ...CURATED_CATEGORIES.fintech.slice(0, 15),
  ...CURATED_CATEGORIES.social.slice(0, 15),
  ...CURATED_CATEGORIES.shop.slice(0, 10),
  ...CURATED_CATEGORIES.crypto.slice(0, 10)
];
